// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: forms.sql

package sqlitegen

import (
	"context"
	"encoding/json"
	"time"
)

const countAllForms = `-- name: CountAllForms :one
SELECT count(*) FROM forms
`

func (q *Queries) CountAllForms(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllForms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFormsByTenant = `-- name: CountFormsByTenant :one
SELECT count(*)
FROM forms f
WHERE f.tenant_id = ?1
  AND (CAST(?2 AS BOOLEAN) IS NULL OR f.is_active = ?2)
  AND (CAST(?3 AS BOOLEAN) IS NULL OR f.is_draft = ?3)
  AND (CAST(?4 AS TEXT) IS NULL OR f.title LIKE '%' || ?4 || '%')
`

type CountFormsByTenantParams struct {
	TenantID int64   `db:"tenant_id" json:"tenant_id"`
	IsActive *bool   `db:"is_active" json:"is_active"`
	IsDraft  *bool   `db:"is_draft" json:"is_draft"`
	Search   *string `db:"search" json:"search"`
}

// Same filters as ListFormsByTenant, for pagination totals.
func (q *Queries) CountFormsByTenant(ctx context.Context, arg CountFormsByTenantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFormsByTenant,
		arg.TenantID,
		arg.IsActive,
		arg.IsDraft,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForm = `-- name: CreateForm :one
INSERT INTO forms (tenant_id, title, slug, description, is_active, start_date, end_date, form_content,
                   public_available, accept_anonymous, is_draft)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, tenant_id, title, slug, description, is_active, start_date, end_date, form_content, created_at, updated_at, public_available, accept_anonymous, is_draft
`

type CreateFormParams struct {
	TenantID        int64           `db:"tenant_id" json:"tenant_id"`
	Title           string          `db:"title" json:"title"`
	Slug            string          `db:"slug" json:"slug"`
	Description     *string         `db:"description" json:"description"`
	IsActive        *bool           `db:"is_active" json:"is_active"`
	StartDate       *time.Time      `db:"start_date" json:"start_date"`
	EndDate         *time.Time      `db:"end_date" json:"end_date"`
	FormContent     json.RawMessage `db:"form_content" json:"form_content"`
	PublicAvailable bool            `db:"public_available" json:"public_available"`
	AcceptAnonymous bool            `db:"accept_anonymous" json:"accept_anonymous"`
	IsDraft         bool            `db:"is_draft" json:"is_draft"`
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRowContext(ctx, createForm,
		arg.TenantID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.IsActive,
		arg.StartDate,
		arg.EndDate,
		arg.FormContent,
		arg.PublicAvailable,
		arg.AcceptAnonymous,
		arg.IsDraft,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.FormContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicAvailable,
		&i.AcceptAnonymous,
		&i.IsDraft,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :execrows
DELETE FROM forms
WHERE id = ? AND tenant_id = ?
`

type DeleteFormParams struct {
	ID       int64 `db:"id" json:"id"`
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteForm(ctx context.Context, arg DeleteFormParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteForm, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAnyFormByID = `-- name: GetAnyFormByID :one
SELECT f.id, f.tenant_id, f.title, f.slug, f.description, f.is_active, f.start_date, f.end_date, f.form_content, f.created_at, f.updated_at, f.public_available, f.accept_anonymous, f.is_draft, t.name AS tenant_name,
       (SELECT count(*) FROM form_submissions s WHERE s.form_id = f.id) AS submission_count
FROM forms f
JOIN tenants t ON t.id = f.tenant_id
WHERE f.id = ?
`

type GetAnyFormByIDRow struct {
	ID              int64           `db:"id" json:"id"`
	TenantID        int64           `db:"tenant_id" json:"tenant_id"`
	Title           string          `db:"title" json:"title"`
	Slug            string          `db:"slug" json:"slug"`
	Description     *string         `db:"description" json:"description"`
	IsActive        *bool           `db:"is_active" json:"is_active"`
	StartDate       *time.Time      `db:"start_date" json:"start_date"`
	EndDate         *time.Time      `db:"end_date" json:"end_date"`
	FormContent     json.RawMessage `db:"form_content" json:"form_content"`
	CreatedAt       *time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       *time.Time      `db:"updated_at" json:"updated_at"`
	PublicAvailable bool            `db:"public_available" json:"public_available"`
	AcceptAnonymous bool            `db:"accept_anonymous" json:"accept_anonymous"`
	IsDraft         bool            `db:"is_draft" json:"is_draft"`
	TenantName      string          `db:"tenant_name" json:"tenant_name"`
	SubmissionCount int64           `db:"submission_count" json:"submission_count"`
}

// Across every tenant, for the read-only /app dashboard.
func (q *Queries) GetAnyFormByID(ctx context.Context, id int64) (GetAnyFormByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAnyFormByID, id)
	var i GetAnyFormByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.FormContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicAvailable,
		&i.AcceptAnonymous,
		&i.IsDraft,
		&i.TenantName,
		&i.SubmissionCount,
	)
	return i, err
}

const getFormByID = `-- name: GetFormByID :one
SELECT f.id, f.tenant_id, f.title, f.slug, f.description, f.is_active, f.start_date, f.end_date, f.form_content, f.created_at, f.updated_at, f.public_available, f.accept_anonymous, f.is_draft, t.name AS tenant_name
FROM forms f
JOIN tenants t ON t.id = f.tenant_id
WHERE f.id = ? AND f.tenant_id = ?
`

type GetFormByIDParams struct {
	ID       int64 `db:"id" json:"id"`
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
}

type GetFormByIDRow struct {
	ID              int64           `db:"id" json:"id"`
	TenantID        int64           `db:"tenant_id" json:"tenant_id"`
	Title           string          `db:"title" json:"title"`
	Slug            string          `db:"slug" json:"slug"`
	Description     *string         `db:"description" json:"description"`
	IsActive        *bool           `db:"is_active" json:"is_active"`
	StartDate       *time.Time      `db:"start_date" json:"start_date"`
	EndDate         *time.Time      `db:"end_date" json:"end_date"`
	FormContent     json.RawMessage `db:"form_content" json:"form_content"`
	CreatedAt       *time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       *time.Time      `db:"updated_at" json:"updated_at"`
	PublicAvailable bool            `db:"public_available" json:"public_available"`
	AcceptAnonymous bool            `db:"accept_anonymous" json:"accept_anonymous"`
	IsDraft         bool            `db:"is_draft" json:"is_draft"`
	TenantName      string          `db:"tenant_name" json:"tenant_name"`
}

// Scoped by tenant so one tenant can never read another tenant's form.
func (q *Queries) GetFormByID(ctx context.Context, arg GetFormByIDParams) (GetFormByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFormByID, arg.ID, arg.TenantID)
	var i GetFormByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.FormContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicAvailable,
		&i.AcceptAnonymous,
		&i.IsDraft,
		&i.TenantName,
	)
	return i, err
}

const getPublicFormBySlug = `-- name: GetPublicFormBySlug :one
SELECT f.id, f.tenant_id, f.title, f.slug, f.description, f.is_active, f.start_date, f.end_date, f.form_content, f.created_at, f.updated_at, f.public_available, f.accept_anonymous, f.is_draft
FROM forms f
JOIN tenants t ON t.id = f.tenant_id
WHERE f.slug = ?
  AND f.is_active
  AND NOT f.is_draft
  AND t.is_active
`

// Published forms of active tenants that are active themselves. The caller
// checks the availability window, so that a form past its end_date can be
// told apart from one that does not exist, and whether signing in is required
// (public_available, accept_anonymous).
func (q *Queries) GetPublicFormBySlug(ctx context.Context, slug string) (Form, error) {
	row := q.db.QueryRowContext(ctx, getPublicFormBySlug, slug)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.FormContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicAvailable,
		&i.AcceptAnonymous,
		&i.IsDraft,
	)
	return i, err
}

const listAllForms = `-- name: ListAllForms :many
SELECT f.id, f.tenant_id, f.title, f.slug, f.description, f.is_active, f.start_date, f.end_date, f.form_content, f.created_at, f.updated_at, f.public_available, f.accept_anonymous, f.is_draft, t.name AS tenant_name,
       (SELECT count(*) FROM form_submissions s WHERE s.form_id = f.id) AS submission_count
FROM forms f
JOIN tenants t ON t.id = f.tenant_id
ORDER BY f.created_at DESC, f.id DESC
LIMIT ?2 OFFSET ?1
`

type ListAllFormsParams struct {
	PageOffset int64 `db:"page_offset" json:"page_offset"`
	PageLimit  int64 `db:"page_limit" json:"page_limit"`
}

type ListAllFormsRow struct {
	ID              int64           `db:"id" json:"id"`
	TenantID        int64           `db:"tenant_id" json:"tenant_id"`
	Title           string          `db:"title" json:"title"`
	Slug            string          `db:"slug" json:"slug"`
	Description     *string         `db:"description" json:"description"`
	IsActive        *bool           `db:"is_active" json:"is_active"`
	StartDate       *time.Time      `db:"start_date" json:"start_date"`
	EndDate         *time.Time      `db:"end_date" json:"end_date"`
	FormContent     json.RawMessage `db:"form_content" json:"form_content"`
	CreatedAt       *time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       *time.Time      `db:"updated_at" json:"updated_at"`
	PublicAvailable bool            `db:"public_available" json:"public_available"`
	AcceptAnonymous bool            `db:"accept_anonymous" json:"accept_anonymous"`
	IsDraft         bool            `db:"is_draft" json:"is_draft"`
	TenantName      string          `db:"tenant_name" json:"tenant_name"`
	SubmissionCount int64           `db:"submission_count" json:"submission_count"`
}

// Across every tenant, for the read-only /app dashboard.
func (q *Queries) ListAllForms(ctx context.Context, arg ListAllFormsParams) ([]ListAllFormsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllForms, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllFormsRow{}
	for rows.Next() {
		var i ListAllFormsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.IsActive,
			&i.StartDate,
			&i.EndDate,
			&i.FormContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicAvailable,
			&i.AcceptAnonymous,
			&i.IsDraft,
			&i.TenantName,
			&i.SubmissionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormsByTenant = `-- name: ListFormsByTenant :many
SELECT f.id, f.tenant_id, f.title, f.slug, f.description, f.is_active, f.start_date, f.end_date, f.form_content, f.created_at, f.updated_at, f.public_available, f.accept_anonymous, f.is_draft, (SELECT count(*) FROM form_submissions s WHERE s.form_id = f.id) AS submission_count
FROM forms f
WHERE f.tenant_id = ?1
  AND (CAST(?2 AS BOOLEAN) IS NULL OR f.is_active = ?2)
  AND (CAST(?3 AS BOOLEAN) IS NULL OR f.is_draft = ?3)
  AND (CAST(?4 AS TEXT) IS NULL OR f.title LIKE '%' || ?4 || '%')
ORDER BY f.created_at DESC, f.id DESC
LIMIT ?6 OFFSET ?5
`

type ListFormsByTenantParams struct {
	TenantID   int64   `db:"tenant_id" json:"tenant_id"`
	IsActive   *bool   `db:"is_active" json:"is_active"`
	IsDraft    *bool   `db:"is_draft" json:"is_draft"`
	Search     *string `db:"search" json:"search"`
	PageOffset int64   `db:"page_offset" json:"page_offset"`
	PageLimit  int64   `db:"page_limit" json:"page_limit"`
}

type ListFormsByTenantRow struct {
	ID              int64           `db:"id" json:"id"`
	TenantID        int64           `db:"tenant_id" json:"tenant_id"`
	Title           string          `db:"title" json:"title"`
	Slug            string          `db:"slug" json:"slug"`
	Description     *string         `db:"description" json:"description"`
	IsActive        *bool           `db:"is_active" json:"is_active"`
	StartDate       *time.Time      `db:"start_date" json:"start_date"`
	EndDate         *time.Time      `db:"end_date" json:"end_date"`
	FormContent     json.RawMessage `db:"form_content" json:"form_content"`
	CreatedAt       *time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       *time.Time      `db:"updated_at" json:"updated_at"`
	PublicAvailable bool            `db:"public_available" json:"public_available"`
	AcceptAnonymous bool            `db:"accept_anonymous" json:"accept_anonymous"`
	IsDraft         bool            `db:"is_draft" json:"is_draft"`
	SubmissionCount int64           `db:"submission_count" json:"submission_count"`
}

// Optional filters: is_active and is_draft (nil = any) and search
// (case-insensitive title match, ASCII only on SQLite).
func (q *Queries) ListFormsByTenant(ctx context.Context, arg ListFormsByTenantParams) ([]ListFormsByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listFormsByTenant,
		arg.TenantID,
		arg.IsActive,
		arg.IsDraft,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFormsByTenantRow{}
	for rows.Next() {
		var i ListFormsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.IsActive,
			&i.StartDate,
			&i.EndDate,
			&i.FormContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicAvailable,
			&i.AcceptAnonymous,
			&i.IsDraft,
			&i.SubmissionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForm = `-- name: UpdateForm :one
UPDATE forms
SET title = ?1,
    slug = ?2,
    description = ?3,
    is_active = ?4,
    start_date = ?5,
    end_date = ?6,
    form_content = ?7,
    public_available = ?8,
    accept_anonymous = ?9,
    is_draft = ?10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?11 AND tenant_id = ?12
  AND (NOT EXISTS (SELECT 1 FROM form_submissions s WHERE s.form_id = forms.id)
       OR (json(forms.form_content) = json(CAST(?13 AS TEXT))
           AND (CAST(?14 AS BOOLEAN) = 0 OR forms.is_draft)))
RETURNING id, tenant_id, title, slug, description, is_active, start_date, end_date, form_content, created_at, updated_at, public_available, accept_anonymous, is_draft
`

type UpdateFormParams struct {
	Title            string          `db:"title" json:"title"`
	Slug             string          `db:"slug" json:"slug"`
	Description      *string         `db:"description" json:"description"`
	IsActive         *bool           `db:"is_active" json:"is_active"`
	StartDate        *time.Time      `db:"start_date" json:"start_date"`
	EndDate          *time.Time      `db:"end_date" json:"end_date"`
	FormContent      json.RawMessage `db:"form_content" json:"form_content"`
	PublicAvailable  bool            `db:"public_available" json:"public_available"`
	AcceptAnonymous  bool            `db:"accept_anonymous" json:"accept_anonymous"`
	IsDraft          bool            `db:"is_draft" json:"is_draft"`
	ID               int64           `db:"id" json:"id"`
	TenantID         int64           `db:"tenant_id" json:"tenant_id"`
	FormContentCheck string          `db:"form_content_check" json:"form_content_check"`
	IsDraftCheck     bool            `db:"is_draft_check" json:"is_draft_check"`
}

// Once a form has submissions its content is locked and it cannot become a
// draft again: no row is updated then, as when the form does not exist.
// form_content_check and is_draft_check repeat the form_content/is_draft
// values passed to the SET clause: sqlc's SQLite query rewriter does not
// dedupe repeated sqlc.arg() references (unlike the pgx engine), and it
// drops named args used as a bare negated boolean (NOT sqlc.arg(x)), so the
// draft-lock check below uses its own args and a CAST(...) = 0 comparison.
func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) (Form, error) {
	row := q.db.QueryRowContext(ctx, updateForm,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.IsActive,
		arg.StartDate,
		arg.EndDate,
		arg.FormContent,
		arg.PublicAvailable,
		arg.AcceptAnonymous,
		arg.IsDraft,
		arg.ID,
		arg.TenantID,
		arg.FormContentCheck,
		arg.IsDraftCheck,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.FormContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicAvailable,
		&i.AcceptAnonymous,
		&i.IsDraft,
	)
	return i, err
}
