// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitegen

import (
	"encoding/json"
	"time"
)

type File struct {
	ID             string    `db:"id" json:"id"`
	TenantID       int64     `db:"tenant_id" json:"tenant_id"`
	Name           string    `db:"name" json:"name"`
	ContentType    string    `db:"content_type" json:"content_type"`
	SizeBytes      int64     `db:"size_bytes" json:"size_bytes"`
	ChecksumSha256 string    `db:"checksum_sha256" json:"checksum_sha256"`
	Data           []byte    `db:"data" json:"data"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
}

type Form struct {
	ID              int64           `db:"id" json:"id"`
	TenantID        int64           `db:"tenant_id" json:"tenant_id"`
	Title           string          `db:"title" json:"title"`
	Slug            string          `db:"slug" json:"slug"`
	Description     *string         `db:"description" json:"description"`
	IsActive        *bool           `db:"is_active" json:"is_active"`
	StartDate       *time.Time      `db:"start_date" json:"start_date"`
	EndDate         *time.Time      `db:"end_date" json:"end_date"`
	FormContent     json.RawMessage `db:"form_content" json:"form_content"`
	CreatedAt       *time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       *time.Time      `db:"updated_at" json:"updated_at"`
	PublicAvailable bool            `db:"public_available" json:"public_available"`
	AcceptAnonymous bool            `db:"accept_anonymous" json:"accept_anonymous"`
	IsDraft         bool            `db:"is_draft" json:"is_draft"`
}

type FormSubmission struct {
	ID          int64           `db:"id" json:"id"`
	FormID      int64           `db:"form_id" json:"form_id"`
	Payload     json.RawMessage `db:"payload" json:"payload"`
	SubmittedAt *time.Time      `db:"submitted_at" json:"submitted_at"`
	UserID      *int64          `db:"user_id" json:"user_id"`
}

type FormWebhook struct {
	ID          int64      `db:"id" json:"id"`
	FormID      int64      `db:"form_id" json:"form_id"`
	TargetUrl   string     `db:"target_url" json:"target_url"`
	SecretToken *string    `db:"secret_token" json:"secret_token"`
	IsActive    *bool      `db:"is_active" json:"is_active"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
}

type SubmissionMetadatum struct {
	ID                    int64      `db:"id" json:"id"`
	SubmissionID          int64      `db:"submission_id" json:"submission_id"`
	IpAddress             *string    `db:"ip_address" json:"ip_address"`
	UserAgent             *string    `db:"user_agent" json:"user_agent"`
	CompletionTimeSeconds *int64     `db:"completion_time_seconds" json:"completion_time_seconds"`
	Referer               *string    `db:"referer" json:"referer"`
	CreatedAt             *time.Time `db:"created_at" json:"created_at"`
}

type Tenant struct {
	ID        int64      `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	ApiKey    string     `db:"api_key" json:"api_key"`
	IsActive  *bool      `db:"is_active" json:"is_active"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID           int64     `db:"id" json:"id"`
	Username     string    `db:"username" json:"username"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	Role         string    `db:"role" json:"role"`
	IsActive     bool      `db:"is_active" json:"is_active"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}
