-- migrate:up
-- Reusable field definitions saved from the form builder. user_id is nullable
-- so a component survives its creator's account being removed.
CREATE TABLE "custom_components" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer REFERENCES "users" ("id"),
  "name" varchar(255) NOT NULL,
  "field" jsonb NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

-- migrate:down
DROP TABLE IF EXISTS "custom_components";
