// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: custom_components.sql

package db

import (
	"context"
	"encoding/json"
)

const createCustomComponent = `-- name: CreateCustomComponent :one
INSERT INTO custom_components (user_id, name, field)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, field, created_at
`

type CreateCustomComponentParams struct {
	UserID *int32          `db:"user_id" json:"user_id"`
	Name   string          `db:"name" json:"name"`
	Field  json.RawMessage `db:"field" json:"field"`
}

func (q *Queries) CreateCustomComponent(ctx context.Context, arg CreateCustomComponentParams) (CustomComponent, error) {
	row := q.db.QueryRow(ctx, createCustomComponent, arg.UserID, arg.Name, arg.Field)
	var i CustomComponent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Field,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomComponents = `-- name: ListCustomComponents :many
SELECT id, user_id, name, field, created_at FROM custom_components
ORDER BY created_at DESC, id DESC
`

// For the builder's "your components" sidebar.
func (q *Queries) ListCustomComponents(ctx context.Context) ([]CustomComponent, error) {
	rows, err := q.db.Query(ctx, listCustomComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomComponent{}
	for rows.Next() {
		var i CustomComponent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Field,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
