// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: forms.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const countAllForms = `-- name: CountAllForms :one
SELECT count(*) FROM forms
`

func (q *Queries) CountAllForms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllForms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFormsByTenant = `-- name: CountFormsByTenant :one
SELECT count(*)
FROM forms f
WHERE f.tenant_id = $1
  AND ($2::boolean IS NULL OR f.is_active = $2)
  AND ($3::text IS NULL OR f.title ILIKE '%' || $3 || '%')
`

type CountFormsByTenantParams struct {
	TenantID int32   `db:"tenant_id" json:"tenant_id"`
	IsActive *bool   `db:"is_active" json:"is_active"`
	Search   *string `db:"search" json:"search"`
}

// Same filters as ListFormsByTenant, for pagination totals.
func (q *Queries) CountFormsByTenant(ctx context.Context, arg CountFormsByTenantParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFormsByTenant, arg.TenantID, arg.IsActive, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForm = `-- name: CreateForm :one
INSERT INTO forms (tenant_id, title, slug, description, is_active, start_date, end_date, form_content)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, title, slug, description, is_active, start_date, end_date, form_content, created_at, updated_at
`

type CreateFormParams struct {
	TenantID    int32           `db:"tenant_id" json:"tenant_id"`
	Title       string          `db:"title" json:"title"`
	Slug        string          `db:"slug" json:"slug"`
	Description *string         `db:"description" json:"description"`
	IsActive    *bool           `db:"is_active" json:"is_active"`
	StartDate   *time.Time      `db:"start_date" json:"start_date"`
	EndDate     *time.Time      `db:"end_date" json:"end_date"`
	FormContent json.RawMessage `db:"form_content" json:"form_content"`
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, createForm,
		arg.TenantID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.IsActive,
		arg.StartDate,
		arg.EndDate,
		arg.FormContent,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.FormContent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :execrows
DELETE FROM forms
WHERE id = $1 AND tenant_id = $2
`

type DeleteFormParams struct {
	ID       int32 `db:"id" json:"id"`
	TenantID int32 `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteForm(ctx context.Context, arg DeleteFormParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForm, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFormByID = `-- name: GetFormByID :one
SELECT f.id, f.tenant_id, f.title, f.slug, f.description, f.is_active, f.start_date, f.end_date, f.form_content, f.created_at, f.updated_at, t.name AS tenant_name
FROM forms f
JOIN tenants t ON t.id = f.tenant_id
WHERE f.id = $1 AND f.tenant_id = $2
`

type GetFormByIDParams struct {
	ID       int32 `db:"id" json:"id"`
	TenantID int32 `db:"tenant_id" json:"tenant_id"`
}

type GetFormByIDRow struct {
	ID          int32           `db:"id" json:"id"`
	TenantID    int32           `db:"tenant_id" json:"tenant_id"`
	Title       string          `db:"title" json:"title"`
	Slug        string          `db:"slug" json:"slug"`
	Description *string         `db:"description" json:"description"`
	IsActive    *bool           `db:"is_active" json:"is_active"`
	StartDate   *time.Time      `db:"start_date" json:"start_date"`
	EndDate     *time.Time      `db:"end_date" json:"end_date"`
	FormContent json.RawMessage `db:"form_content" json:"form_content"`
	CreatedAt   *time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time      `db:"updated_at" json:"updated_at"`
	TenantName  string          `db:"tenant_name" json:"tenant_name"`
}

// Scoped by tenant so one tenant can never read another tenant's form.
func (q *Queries) GetFormByID(ctx context.Context, arg GetFormByIDParams) (GetFormByIDRow, error) {
	row := q.db.QueryRow(ctx, getFormByID, arg.ID, arg.TenantID)
	var i GetFormByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.FormContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantName,
	)
	return i, err
}

const getPublicFormBySlug = `-- name: GetPublicFormBySlug :one
SELECT f.id, f.tenant_id, f.title, f.slug, f.description, f.is_active, f.start_date, f.end_date, f.form_content, f.created_at, f.updated_at
FROM forms f
JOIN tenants t ON t.id = f.tenant_id
WHERE f.slug = $1
  AND f.is_active
  AND t.is_active
  AND (f.start_date IS NULL OR f.start_date <= now())
  AND (f.end_date IS NULL OR f.end_date > now())
`

// Public access: the form and its tenant must be active and inside the availability window.
func (q *Queries) GetPublicFormBySlug(ctx context.Context, slug string) (Form, error) {
	row := q.db.QueryRow(ctx, getPublicFormBySlug, slug)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.FormContent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllForms = `-- name: ListAllForms :many
SELECT f.id, f.tenant_id, f.title, f.slug, f.description, f.is_active, f.start_date, f.end_date, f.form_content, f.created_at, f.updated_at, t.name AS tenant_name,
       (SELECT count(*) FROM form_submissions s WHERE s.form_id = f.id) AS submission_count
FROM forms f
JOIN tenants t ON t.id = f.tenant_id
ORDER BY f.created_at DESC, f.id DESC
LIMIT $2 OFFSET $1
`

type ListAllFormsParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

type ListAllFormsRow struct {
	ID              int32           `db:"id" json:"id"`
	TenantID        int32           `db:"tenant_id" json:"tenant_id"`
	Title           string          `db:"title" json:"title"`
	Slug            string          `db:"slug" json:"slug"`
	Description     *string         `db:"description" json:"description"`
	IsActive        *bool           `db:"is_active" json:"is_active"`
	StartDate       *time.Time      `db:"start_date" json:"start_date"`
	EndDate         *time.Time      `db:"end_date" json:"end_date"`
	FormContent     json.RawMessage `db:"form_content" json:"form_content"`
	CreatedAt       *time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       *time.Time      `db:"updated_at" json:"updated_at"`
	TenantName      string          `db:"tenant_name" json:"tenant_name"`
	SubmissionCount int64           `db:"submission_count" json:"submission_count"`
}

// Across every tenant, for the read-only /app dashboard.
func (q *Queries) ListAllForms(ctx context.Context, arg ListAllFormsParams) ([]ListAllFormsRow, error) {
	rows, err := q.db.Query(ctx, listAllForms, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllFormsRow{}
	for rows.Next() {
		var i ListAllFormsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.IsActive,
			&i.StartDate,
			&i.EndDate,
			&i.FormContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantName,
			&i.SubmissionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormsByTenant = `-- name: ListFormsByTenant :many
SELECT f.id, f.tenant_id, f.title, f.slug, f.description, f.is_active, f.start_date, f.end_date, f.form_content, f.created_at, f.updated_at, (SELECT count(*) FROM form_submissions s WHERE s.form_id = f.id) AS submission_count
FROM forms f
WHERE f.tenant_id = $1
  AND ($2::boolean IS NULL OR f.is_active = $2)
  AND ($3::text IS NULL OR f.title ILIKE '%' || $3 || '%')
ORDER BY f.created_at DESC, f.id DESC
LIMIT $5 OFFSET $4
`

type ListFormsByTenantParams struct {
	TenantID   int32   `db:"tenant_id" json:"tenant_id"`
	IsActive   *bool   `db:"is_active" json:"is_active"`
	Search     *string `db:"search" json:"search"`
	PageOffset int32   `db:"page_offset" json:"page_offset"`
	PageLimit  int32   `db:"page_limit" json:"page_limit"`
}

type ListFormsByTenantRow struct {
	ID              int32           `db:"id" json:"id"`
	TenantID        int32           `db:"tenant_id" json:"tenant_id"`
	Title           string          `db:"title" json:"title"`
	Slug            string          `db:"slug" json:"slug"`
	Description     *string         `db:"description" json:"description"`
	IsActive        *bool           `db:"is_active" json:"is_active"`
	StartDate       *time.Time      `db:"start_date" json:"start_date"`
	EndDate         *time.Time      `db:"end_date" json:"end_date"`
	FormContent     json.RawMessage `db:"form_content" json:"form_content"`
	CreatedAt       *time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       *time.Time      `db:"updated_at" json:"updated_at"`
	SubmissionCount int64           `db:"submission_count" json:"submission_count"`
}

// Optional filters: is_active (nil = any) and search (case-insensitive title match).
func (q *Queries) ListFormsByTenant(ctx context.Context, arg ListFormsByTenantParams) ([]ListFormsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listFormsByTenant,
		arg.TenantID,
		arg.IsActive,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFormsByTenantRow{}
	for rows.Next() {
		var i ListFormsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.IsActive,
			&i.StartDate,
			&i.EndDate,
			&i.FormContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmissionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForm = `-- name: UpdateForm :one
UPDATE forms
SET title = $3,
    slug = $4,
    description = $5,
    is_active = $6,
    start_date = $7,
    end_date = $8,
    form_content = $9,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, title, slug, description, is_active, start_date, end_date, form_content, created_at, updated_at
`

type UpdateFormParams struct {
	ID          int32           `db:"id" json:"id"`
	TenantID    int32           `db:"tenant_id" json:"tenant_id"`
	Title       string          `db:"title" json:"title"`
	Slug        string          `db:"slug" json:"slug"`
	Description *string         `db:"description" json:"description"`
	IsActive    *bool           `db:"is_active" json:"is_active"`
	StartDate   *time.Time      `db:"start_date" json:"start_date"`
	EndDate     *time.Time      `db:"end_date" json:"end_date"`
	FormContent json.RawMessage `db:"form_content" json:"form_content"`
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, updateForm,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.IsActive,
		arg.StartDate,
		arg.EndDate,
		arg.FormContent,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.FormContent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
