// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"encoding/json"
	"time"
)

type File struct {
	ID             string    `db:"id" json:"id"`
	TenantID       int32     `db:"tenant_id" json:"tenant_id"`
	Name           string    `db:"name" json:"name"`
	ContentType    string    `db:"content_type" json:"content_type"`
	SizeBytes      int64     `db:"size_bytes" json:"size_bytes"`
	ChecksumSha256 string    `db:"checksum_sha256" json:"checksum_sha256"`
	Data           []byte    `db:"data" json:"data"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
}

type Form struct {
	ID          int32           `db:"id" json:"id"`
	TenantID    int32           `db:"tenant_id" json:"tenant_id"`
	Title       string          `db:"title" json:"title"`
	Slug        string          `db:"slug" json:"slug"`
	Description *string         `db:"description" json:"description"`
	IsActive    *bool           `db:"is_active" json:"is_active"`
	StartDate   *time.Time      `db:"start_date" json:"start_date"`
	EndDate     *time.Time      `db:"end_date" json:"end_date"`
	FormContent json.RawMessage `db:"form_content" json:"form_content"`
	CreatedAt   *time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time      `db:"updated_at" json:"updated_at"`
}

type FormSubmission struct {
	ID          int32           `db:"id" json:"id"`
	FormID      int32           `db:"form_id" json:"form_id"`
	Payload     json.RawMessage `db:"payload" json:"payload"`
	SubmittedAt *time.Time      `db:"submitted_at" json:"submitted_at"`
}

type FormWebhook struct {
	ID          int32      `db:"id" json:"id"`
	FormID      int32      `db:"form_id" json:"form_id"`
	TargetUrl   string     `db:"target_url" json:"target_url"`
	SecretToken *string    `db:"secret_token" json:"secret_token"`
	IsActive    *bool      `db:"is_active" json:"is_active"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
}

type SubmissionMetadatum struct {
	ID                    int32      `db:"id" json:"id"`
	SubmissionID          int32      `db:"submission_id" json:"submission_id"`
	IpAddress             *string    `db:"ip_address" json:"ip_address"`
	UserAgent             *string    `db:"user_agent" json:"user_agent"`
	CompletionTimeSeconds *int32     `db:"completion_time_seconds" json:"completion_time_seconds"`
	Referer               *string    `db:"referer" json:"referer"`
	CreatedAt             *time.Time `db:"created_at" json:"created_at"`
}

type Tenant struct {
	ID        int32      `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	ApiKey    string     `db:"api_key" json:"api_key"`
	IsActive  *bool      `db:"is_active" json:"is_active"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}
