// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CountAllFiles(ctx context.Context) (int64, error)
	CountAllForms(ctx context.Context) (int64, error)
	// Same filters as ListFormsByTenant, for pagination totals.
	CountFormsByTenant(ctx context.Context, arg CountFormsByTenantParams) (int64, error)
	// Returns the metadata only: the blob was just sent by the caller. The id is
	// generated by the application (not the database) so it is portable across
	// database engines.
	CreateFile(ctx context.Context, arg CreateFileParams) (CreateFileRow, error)
	CreateForm(ctx context.Context, arg CreateFormParams) (Form, error)
	CreateFormSubmission(ctx context.Context, arg CreateFormSubmissionParams) (FormSubmission, error)
	CreateFormWebhook(ctx context.Context, arg CreateFormWebhookParams) (FormWebhook, error)
	CreateSubmissionMetadata(ctx context.Context, arg CreateSubmissionMetadataParams) (SubmissionMetadatum, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// For bootstrapping accounts: an existing user is left untouched.
	CreateUserIfNotExists(ctx context.Context, arg CreateUserIfNotExistsParams) (int64, error)
	// Scoped by tenant so one tenant can never remove another tenant's file.
	DeleteFile(ctx context.Context, arg DeleteFileParams) (int64, error)
	DeleteForm(ctx context.Context, arg DeleteFormParams) (int64, error)
	// Across every tenant, for the read-only /app dashboard.
	GetAnyFormByID(ctx context.Context, id int32) (GetAnyFormByIDRow, error)
	GetFileByID(ctx context.Context, id string) (File, error)
	// Scoped by tenant so one tenant can never read another tenant's form.
	GetFormByID(ctx context.Context, arg GetFormByIDParams) (GetFormByIDRow, error)
	// Published forms of active tenants that are active themselves. The caller
	// checks the availability window, so that a form past its end_date can be
	// told apart from one that does not exist, and whether signing in is required
	// (public_available, accept_anonymous).
	GetPublicFormBySlug(ctx context.Context, slug string) (Form, error)
	GetTenantByAPIKey(ctx context.Context, apiKey string) (Tenant, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListActiveWebhooksByForm(ctx context.Context, formID int32) ([]FormWebhook, error)
	// Metadata only, across every tenant, for the read-only /app dashboard.
	ListAllFiles(ctx context.Context, arg ListAllFilesParams) ([]ListAllFilesRow, error)
	// Across every tenant, for the read-only /app dashboard.
	ListAllForms(ctx context.Context, arg ListAllFormsParams) ([]ListAllFormsRow, error)
	// Same as ListSubmissionsByForm without pagination, for exports.
	ListAllSubmissionsByForm(ctx context.Context, arg ListAllSubmissionsByFormParams) ([]ListAllSubmissionsByFormRow, error)
	// Optional filters: is_active and is_draft (nil = any) and search
	// (case-insensitive title match).
	ListFormsByTenant(ctx context.Context, arg ListFormsByTenantParams) ([]ListFormsByTenantRow, error)
	// Scoped by tenant through the owning form; metadata is optional (LEFT JOIN).
	ListSubmissionsByForm(ctx context.Context, arg ListSubmissionsByFormParams) ([]ListSubmissionsByFormRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Once a form has submissions its content is locked and it cannot become a
	// draft again: no row is updated then, as when the form does not exist.
	UpdateForm(ctx context.Context, arg UpdateFormParams) (Form, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
