// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: submissions.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const countAllSubmissions = `-- name: CountAllSubmissions :one
SELECT count(*) FROM form_submissions
`

// Across every tenant, for the read-only /app dashboard.
func (q *Queries) CountAllSubmissions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllSubmissions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllSubmissionsToday = `-- name: CountAllSubmissionsToday :one
SELECT count(*) FROM form_submissions WHERE submitted_at >= date_trunc('day', now())
`

// Across every tenant, for the read-only /app dashboard.
func (q *Queries) CountAllSubmissionsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllSubmissionsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFormSubmission = `-- name: CreateFormSubmission :one
INSERT INTO form_submissions (form_id, payload, user_id)
VALUES ($1, $2, $3)
RETURNING id, form_id, payload, submitted_at, user_id
`

type CreateFormSubmissionParams struct {
	FormID  int32           `db:"form_id" json:"form_id"`
	Payload json.RawMessage `db:"payload" json:"payload"`
	UserID  *int32          `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateFormSubmission(ctx context.Context, arg CreateFormSubmissionParams) (FormSubmission, error) {
	row := q.db.QueryRow(ctx, createFormSubmission, arg.FormID, arg.Payload, arg.UserID)
	var i FormSubmission
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Payload,
		&i.SubmittedAt,
		&i.UserID,
	)
	return i, err
}

const createSubmissionMetadata = `-- name: CreateSubmissionMetadata :one
INSERT INTO submission_metadata (submission_id, ip_address, user_agent, completion_time_seconds, referer)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, submission_id, ip_address, user_agent, completion_time_seconds, referer, created_at
`

type CreateSubmissionMetadataParams struct {
	SubmissionID          int32   `db:"submission_id" json:"submission_id"`
	IpAddress             *string `db:"ip_address" json:"ip_address"`
	UserAgent             *string `db:"user_agent" json:"user_agent"`
	CompletionTimeSeconds *int32  `db:"completion_time_seconds" json:"completion_time_seconds"`
	Referer               *string `db:"referer" json:"referer"`
}

func (q *Queries) CreateSubmissionMetadata(ctx context.Context, arg CreateSubmissionMetadataParams) (SubmissionMetadatum, error) {
	row := q.db.QueryRow(ctx, createSubmissionMetadata,
		arg.SubmissionID,
		arg.IpAddress,
		arg.UserAgent,
		arg.CompletionTimeSeconds,
		arg.Referer,
	)
	var i SubmissionMetadatum
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CompletionTimeSeconds,
		&i.Referer,
		&i.CreatedAt,
	)
	return i, err
}

const listAllSubmissionsByForm = `-- name: ListAllSubmissionsByForm :many
SELECT s.id, s.form_id, s.payload, s.submitted_at, s.user_id, m.ip_address, m.user_agent, m.completion_time_seconds, m.referer
FROM form_submissions s
JOIN forms f ON f.id = s.form_id
LEFT JOIN submission_metadata m ON m.submission_id = s.id
WHERE s.form_id = $1 AND f.tenant_id = $2
ORDER BY s.submitted_at DESC, s.id DESC
`

type ListAllSubmissionsByFormParams struct {
	FormID   int32 `db:"form_id" json:"form_id"`
	TenantID int32 `db:"tenant_id" json:"tenant_id"`
}

type ListAllSubmissionsByFormRow struct {
	ID                    int32           `db:"id" json:"id"`
	FormID                int32           `db:"form_id" json:"form_id"`
	Payload               json.RawMessage `db:"payload" json:"payload"`
	SubmittedAt           *time.Time      `db:"submitted_at" json:"submitted_at"`
	UserID                *int32          `db:"user_id" json:"user_id"`
	IpAddress             *string         `db:"ip_address" json:"ip_address"`
	UserAgent             *string         `db:"user_agent" json:"user_agent"`
	CompletionTimeSeconds *int32          `db:"completion_time_seconds" json:"completion_time_seconds"`
	Referer               *string         `db:"referer" json:"referer"`
}

// Same as ListSubmissionsByForm without pagination, for exports.
func (q *Queries) ListAllSubmissionsByForm(ctx context.Context, arg ListAllSubmissionsByFormParams) ([]ListAllSubmissionsByFormRow, error) {
	rows, err := q.db.Query(ctx, listAllSubmissionsByForm, arg.FormID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSubmissionsByFormRow{}
	for rows.Next() {
		var i ListAllSubmissionsByFormRow
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Payload,
			&i.SubmittedAt,
			&i.UserID,
			&i.IpAddress,
			&i.UserAgent,
			&i.CompletionTimeSeconds,
			&i.Referer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByForm = `-- name: ListSubmissionsByForm :many
SELECT s.id, s.form_id, s.payload, s.submitted_at, s.user_id, m.ip_address, m.user_agent, m.completion_time_seconds, m.referer
FROM form_submissions s
JOIN forms f ON f.id = s.form_id
LEFT JOIN submission_metadata m ON m.submission_id = s.id
WHERE s.form_id = $1 AND f.tenant_id = $2
ORDER BY s.submitted_at DESC, s.id DESC
LIMIT $4 OFFSET $3
`

type ListSubmissionsByFormParams struct {
	FormID     int32 `db:"form_id" json:"form_id"`
	TenantID   int32 `db:"tenant_id" json:"tenant_id"`
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

type ListSubmissionsByFormRow struct {
	ID                    int32           `db:"id" json:"id"`
	FormID                int32           `db:"form_id" json:"form_id"`
	Payload               json.RawMessage `db:"payload" json:"payload"`
	SubmittedAt           *time.Time      `db:"submitted_at" json:"submitted_at"`
	UserID                *int32          `db:"user_id" json:"user_id"`
	IpAddress             *string         `db:"ip_address" json:"ip_address"`
	UserAgent             *string         `db:"user_agent" json:"user_agent"`
	CompletionTimeSeconds *int32          `db:"completion_time_seconds" json:"completion_time_seconds"`
	Referer               *string         `db:"referer" json:"referer"`
}

// Scoped by tenant through the owning form; metadata is optional (LEFT JOIN).
func (q *Queries) ListSubmissionsByForm(ctx context.Context, arg ListSubmissionsByFormParams) ([]ListSubmissionsByFormRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByForm,
		arg.FormID,
		arg.TenantID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsByFormRow{}
	for rows.Next() {
		var i ListSubmissionsByFormRow
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Payload,
			&i.SubmittedAt,
			&i.UserID,
			&i.IpAddress,
			&i.UserAgent,
			&i.CompletionTimeSeconds,
			&i.Referer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
