// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tenants.sql

package db

import (
	"context"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, api_key)
VALUES ($1, $2)
RETURNING id, name, api_key, is_active, created_at
`

type CreateTenantParams struct {
	Name   string `db:"name" json:"name"`
	ApiKey string `db:"api_key" json:"api_key"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.ApiKey)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByAPIKey = `-- name: GetTenantByAPIKey :one
SELECT id, name, api_key, is_active, created_at FROM tenants
WHERE api_key = $1 AND is_active
`

func (q *Queries) GetTenantByAPIKey(ctx context.Context, apiKey string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByAPIKey, apiKey)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
