// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const countUserIdentities = `-- name: CountUserIdentities :one
SELECT COUNT(*) FROM user_identities
WHERE user_id = $1
`

func (q *Queries) CountUserIdentities(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUserIdentities, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, username, password_hash, role, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Username     string   `db:"username" json:"username"`
	PasswordHash *string  `db:"password_hash" json:"password_hash"`
	Role         UserRole `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserIfNotExists = `-- name: CreateUserIfNotExists :execrows
INSERT INTO users (username, password_hash, role)
VALUES ($1, $2, $3)
ON CONFLICT (username) DO NOTHING
`

type CreateUserIfNotExistsParams struct {
	Username     string   `db:"username" json:"username"`
	PasswordHash *string  `db:"password_hash" json:"password_hash"`
	Role         UserRole `db:"role" json:"role"`
}

// For bootstrapping accounts: an existing user is left untouched.
func (q *Queries) CreateUserIfNotExists(ctx context.Context, arg CreateUserIfNotExistsParams) (int64, error) {
	result, err := q.db.Exec(ctx, createUserIfNotExists, arg.Username, arg.PasswordHash, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUserWithIdentity = `-- name: CreateUserWithIdentity :one
WITH new_user AS (
  INSERT INTO users (username, role)
  VALUES ($1, $2)
  RETURNING id, username, password_hash, role, is_active, created_at, updated_at
), new_identity AS (
  INSERT INTO user_identities (user_id, issuer, subject, email)
  SELECT id, $3, $4, $5 FROM new_user
)
SELECT id, username, password_hash, role, is_active, created_at, updated_at FROM new_user
`

type CreateUserWithIdentityParams struct {
	Username string   `db:"username" json:"username"`
	Role     UserRole `db:"role" json:"role"`
	Issuer   string   `db:"issuer" json:"issuer"`
	Subject  string   `db:"subject" json:"subject"`
	Email    *string  `db:"email" json:"email"`
}

type CreateUserWithIdentityRow struct {
	ID           int32     `db:"id" json:"id"`
	Username     string    `db:"username" json:"username"`
	PasswordHash *string   `db:"password_hash" json:"password_hash"`
	Role         UserRole  `db:"role" json:"role"`
	IsActive     bool      `db:"is_active" json:"is_active"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}

// Creates a user without a password and links the identity to it, in one
// statement so neither can exist without the other.
func (q *Queries) CreateUserWithIdentity(ctx context.Context, arg CreateUserWithIdentityParams) (CreateUserWithIdentityRow, error) {
	row := q.db.QueryRow(ctx, createUserWithIdentity,
		arg.Username,
		arg.Role,
		arg.Issuer,
		arg.Subject,
		arg.Email,
	)
	var i CreateUserWithIdentityRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, is_active, created_at, updated_at FROM users
WHERE id = $1 AND is_active
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT users.id, users.username, users.password_hash, users.role, users.is_active, users.created_at, users.updated_at FROM users
JOIN user_identities ON user_identities.user_id = users.id
WHERE user_identities.issuer = $1 AND user_identities.subject = $2
`

type GetUserByIdentityParams struct {
	Issuer  string `db:"issuer" json:"issuer"`
	Subject string `db:"subject" json:"subject"`
}

// The user linked to an external OIDC identity, active or not: the caller
// refuses inactive users rather than mistaking them for unknown identities.
func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Issuer, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, is_active, created_at, updated_at FROM users
WHERE username = $1 AND is_active
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role, is_active, created_at, updated_at FROM users
ORDER BY id
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchUserIdentity = `-- name: TouchUserIdentity :exec
UPDATE user_identities
SET last_login_at = now(),
    email = $1
WHERE issuer = $2 AND subject = $3
`

type TouchUserIdentityParams struct {
	Email   *string `db:"email" json:"email"`
	Issuer  string  `db:"issuer" json:"issuer"`
	Subject string  `db:"subject" json:"subject"`
}

// Records a sign-in through an identity and refreshes its email.
func (q *Queries) TouchUserIdentity(ctx context.Context, arg TouchUserIdentityParams) error {
	_, err := q.db.Exec(ctx, touchUserIdentity, arg.Email, arg.Issuer, arg.Subject)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, username, password_hash, role, is_active, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   int32    `db:"id" json:"id"`
	Role UserRole `db:"role" json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
