// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, username, password_hash, role, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Username     string   `db:"username" json:"username"`
	PasswordHash string   `db:"password_hash" json:"password_hash"`
	Role         UserRole `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserIfNotExists = `-- name: CreateUserIfNotExists :execrows
INSERT INTO users (username, password_hash, role)
VALUES ($1, $2, $3)
ON CONFLICT (username) DO NOTHING
`

type CreateUserIfNotExistsParams struct {
	Username     string   `db:"username" json:"username"`
	PasswordHash string   `db:"password_hash" json:"password_hash"`
	Role         UserRole `db:"role" json:"role"`
}

// For bootstrapping accounts: an existing user is left untouched.
func (q *Queries) CreateUserIfNotExists(ctx context.Context, arg CreateUserIfNotExistsParams) (int64, error) {
	result, err := q.db.Exec(ctx, createUserIfNotExists, arg.Username, arg.PasswordHash, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, is_active, created_at, updated_at FROM users
WHERE id = $1 AND is_active
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, is_active, created_at, updated_at FROM users
WHERE username = $1 AND is_active
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role, is_active, created_at, updated_at FROM users
ORDER BY id
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, username, password_hash, role, is_active, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   int32    `db:"id" json:"id"`
	Role UserRole `db:"role" json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
