// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: webhooks.sql

package db

import (
	"context"
)

const createFormWebhook = `-- name: CreateFormWebhook :one
INSERT INTO form_webhooks (form_id, target_url, secret_token)
VALUES ($1, $2, $3)
RETURNING id, form_id, target_url, secret_token, is_active, created_at
`

type CreateFormWebhookParams struct {
	FormID      int32   `db:"form_id" json:"form_id"`
	TargetUrl   string  `db:"target_url" json:"target_url"`
	SecretToken *string `db:"secret_token" json:"secret_token"`
}

func (q *Queries) CreateFormWebhook(ctx context.Context, arg CreateFormWebhookParams) (FormWebhook, error) {
	row := q.db.QueryRow(ctx, createFormWebhook, arg.FormID, arg.TargetUrl, arg.SecretToken)
	var i FormWebhook
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.TargetUrl,
		&i.SecretToken,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveWebhooksByForm = `-- name: ListActiveWebhooksByForm :many
SELECT id, form_id, target_url, secret_token, is_active, created_at FROM form_webhooks
WHERE form_id = $1 AND is_active
ORDER BY id
`

func (q *Queries) ListActiveWebhooksByForm(ctx context.Context, formID int32) ([]FormWebhook, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooksByForm, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormWebhook{}
	for rows.Next() {
		var i FormWebhook
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.TargetUrl,
			&i.SecretToken,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
