// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/files": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Stores the file sent in the \"file\" field of a multipart form. Files are limited to 10 MiB and can then be read publicly at the returned url.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Upload a file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "File uploaded",
                        "schema": {
                            "$ref": "#/definitions/handlers.FileResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid, missing, empty or too large file",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/files/{id}": {
            "get": {
                "description": "Returns the raw content of a file, with its stored content type. Supports HEAD, Range and conditional (ETag) requests. No API key is needed: the file ID is unguessable.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Download a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deletes one of the authenticated tenant's files.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Delete a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "File deleted"
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/forms": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Lists the authenticated tenant's forms, newest first, with their submission counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "List forms",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Only forms in this state",
                        "name": "is_active",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive title substring",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of forms to skip",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum number of forms to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Page of forms",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a form owned by the authenticated tenant. The slug must be unique across all forms.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Create a form",
                "parameters": [
                    {
                        "description": "Form to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.FormRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Form created",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Slug already exists",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/forms/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns one of the authenticated tenant's forms.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Get a form",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Form",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid form ID",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Replaces every field of one of the authenticated tenant's forms. Omitted optional fields are cleared; an omitted is_active makes the form active.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Update a form",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New state of the form",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.FormRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Form updated",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Slug already exists",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deletes one of the authenticated tenant's forms. Forms that have submissions or webhooks cannot be deleted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Delete a form",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Form deleted"
                    },
                    "400": {
                        "description": "Invalid form ID",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Form has submissions or webhooks",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/forms/{id}/submissions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Lists the submissions of one of the authenticated tenant's forms, newest first, with their metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "submissions"
                ],
                "summary": "List form submissions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of submissions to skip",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum number of submissions to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Page of submissions",
                        "schema": {
                            "$ref": "#/definitions/handlers.SubmissionListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/forms/{id}/webhooks": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Lists the active webhooks of one of the authenticated tenant's forms, oldest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "List webhooks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Webhooks",
                        "schema": {
                            "$ref": "#/definitions/handlers.WebhookListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid form ID",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Registers an endpoint notified of the form's new submissions. The target must be a public http(s) URL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Create a webhook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Webhook to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateWebhookRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Webhook created",
                        "schema": {
                            "$ref": "#/definitions/handlers.WebhookResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Reports whether the service is up and running.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is up",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/public/forms/{slug}": {
            "get": {
                "description": "Returns the form with the given slug if it is active, its tenant is active and now is inside its availability window.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Get a public form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Form",
                        "schema": {
                            "$ref": "#/definitions/handlers.PublicFormResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found or not available",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/public/forms/{slug}/submissions": {
            "post": {
                "description": "Stores the answers to a form that can currently be filled in, along with the client's IP address, user agent and referer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "submissions",
                    "public"
                ],
                "summary": "Submit a form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Answers",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateSubmissionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Submission stored",
                        "schema": {
                            "$ref": "#/definitions/handlers.SubmissionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found or not available",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/tenants": {
            "post": {
                "description": "Registers a new tenant and returns it with a freshly generated API key. The key is shown only once; send it in the X-API-Key header of authenticated requests.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenants"
                ],
                "summary": "Create a tenant",
                "parameters": [
                    {
                        "description": "Tenant to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateTenantRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tenant created",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateTenantResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/tenants/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the tenant that owns the API key of the request.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenants"
                ],
                "summary": "Get the current tenant",
                "responses": {
                    "200": {
                        "description": "Authenticated tenant",
                        "schema": {
                            "$ref": "#/definitions/handlers.TenantResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errors.Code": {
            "type": "string",
            "enum": [
                "invalid_argument",
                "unauthorized",
                "forbidden",
                "not_found",
                "conflict",
                "internal"
            ],
            "x-enum-varnames": [
                "CodeInvalidArgument",
                "CodeUnauthorized",
                "CodeForbidden",
                "CodeNotFound",
                "CodeConflict",
                "CodeInternal"
            ]
        },
        "errors.HTTPErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/errors.Code"
                        }
                    ],
                    "example": "not_found"
                },
                "message": {
                    "type": "string",
                    "example": "form not found"
                }
            }
        },
        "handler.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "UP"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                }
            }
        },
        "handlers.CreateSubmissionRequest": {
            "type": "object",
            "properties": {
                "completion_time_seconds": {
                    "description": "CompletionTimeSeconds is how long the respondent took to fill the form in.",
                    "type": "integer",
                    "minimum": 0,
                    "example": 95
                },
                "payload": {
                    "description": "Payload holds the answers; any JSON value but null.",
                    "type": "object"
                }
            }
        },
        "handlers.CreateTenantRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Acme Inc."
                }
            }
        },
        "handlers.CreateTenantResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string",
                    "example": "3f1c...e9a0"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Acme Inc."
                }
            }
        },
        "handlers.CreateWebhookRequest": {
            "type": "object",
            "properties": {
                "secret_token": {
                    "description": "SecretToken, when set, is used to sign deliveries. It is never returned.",
                    "type": "string",
                    "example": "s3cr3t"
                },
                "target_url": {
                    "description": "TargetURL must be a public http(s) URL.",
                    "type": "string",
                    "example": "https://example.com/hooks/forms"
                }
            }
        },
        "handlers.FileResponse": {
            "type": "object",
            "properties": {
                "checksum_sha256": {
                    "description": "Checksum is the hex-encoded SHA-256 of the content.",
                    "type": "string",
                    "example": "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
                },
                "content_type": {
                    "type": "string",
                    "example": "image/png"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "0b6a3b2e-8f1c-4c4e-9d5e-2f1a7c3b9e10"
                },
                "name": {
                    "type": "string",
                    "example": "logo.png"
                },
                "size": {
                    "type": "integer",
                    "example": 2048
                },
                "url": {
                    "type": "string",
                    "example": "/files/0b6a3b2e-8f1c-4c4e-9d5e-2f1a7c3b9e10"
                }
            }
        },
        "handlers.FormDetailsResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "object"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Get in touch with our team"
                },
                "end_date": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "slug": {
                    "type": "string",
                    "example": "contact-us"
                },
                "start_date": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "tenant_id": {
                    "type": "integer",
                    "example": 1
                },
                "tenant_name": {
                    "type": "string",
                    "example": "Acme Inc."
                },
                "title": {
                    "type": "string",
                    "example": "Contact us"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                }
            }
        },
        "handlers.FormListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.FormSummaryResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handlers.FormRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Content is the form definition (fields, layout); any JSON value but null.",
                    "type": "object"
                },
                "description": {
                    "type": "string",
                    "example": "Get in touch with our team"
                },
                "end_date": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "is_active": {
                    "description": "IsActive defaults to true when omitted.",
                    "type": "boolean",
                    "example": true
                },
                "slug": {
                    "type": "string",
                    "example": "contact-us"
                },
                "start_date": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Contact us"
                }
            }
        },
        "handlers.FormResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "object"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Get in touch with our team"
                },
                "end_date": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "slug": {
                    "type": "string",
                    "example": "contact-us"
                },
                "start_date": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "tenant_id": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Contact us"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                }
            }
        },
        "handlers.FormSummaryResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "object"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Get in touch with our team"
                },
                "end_date": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "slug": {
                    "type": "string",
                    "example": "contact-us"
                },
                "start_date": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "submission_count": {
                    "type": "integer",
                    "example": 42
                },
                "tenant_id": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Contact us"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                }
            }
        },
        "handlers.MetadataResponse": {
            "type": "object",
            "properties": {
                "completion_time_seconds": {
                    "type": "integer",
                    "example": 95
                },
                "ip_address": {
                    "type": "string",
                    "example": "203.0.113.7"
                },
                "referer": {
                    "type": "string",
                    "example": "https://example.com/contact"
                },
                "user_agent": {
                    "type": "string",
                    "example": "Mozilla/5.0"
                }
            }
        },
        "handlers.PublicFormResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "object"
                },
                "description": {
                    "type": "string",
                    "example": "Get in touch with our team"
                },
                "end_date": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "slug": {
                    "type": "string",
                    "example": "contact-us"
                },
                "title": {
                    "type": "string",
                    "example": "Contact us"
                }
            }
        },
        "handlers.SubmissionListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.SubmissionResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "handlers.SubmissionResponse": {
            "type": "object",
            "properties": {
                "form_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "metadata": {
                    "$ref": "#/definitions/handlers.MetadataResponse"
                },
                "payload": {
                    "type": "object"
                },
                "submitted_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                }
            }
        },
        "handlers.TenantResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Acme Inc."
                }
            }
        },
        "handlers.WebhookListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.WebhookResponse"
                    }
                }
            }
        },
        "handlers.WebhookResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "form_id": {
                    "type": "integer",
                    "example": 1
                },
                "has_secret": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "target_url": {
                    "type": "string",
                    "example": "https://example.com/hooks/forms"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key of the tenant, returned when the tenant is created.",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "App API",
	Description:      "REST API of the application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
