// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Returns the user authenticated by the bearer token or Basic credentials.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get the current user",
                "responses": {
                    "200": {
                        "description": "Signed-in user",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Not signed in",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Checks the HTTP Basic credentials (\"Authorization: Basic \" + btoa(username + \":\" + password)) and returns a JWT access token to send as \"Authorization: Bearer \u003ctoken\u003e\".",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign in",
                "responses": {
                    "200": {
                        "description": "Signed in",
                        "schema": {
                            "$ref": "#/definitions/handlers.TokenResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Creates an account with the BASIC role. Usernames are case-insensitive.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign up",
                "parameters": [
                    {
                        "description": "Credentials of the new account",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Account created",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid username or password",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Username already taken",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/files": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Stores the file sent in the \"file\" field of a multipart form. Files are limited to 10 MiB and can then be read publicly at the returned url.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Upload a file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "File uploaded",
                        "schema": {
                            "$ref": "#/definitions/handlers.FileResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid, missing, empty or too large file",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/files/{id}": {
            "get": {
                "description": "Returns the raw content of a file, with its stored content type. Supports HEAD, Range and conditional (ETag) requests. No API key is needed: the file ID is unguessable. Set download=1 to have browsers save the file instead of displaying it.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Download a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Serve the file as an attachment",
                        "name": "download",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deletes one of the authenticated tenant's files.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Delete a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "File deleted"
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/forms": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Lists the authenticated tenant's forms, newest first, with their submission counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "List forms",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Only forms in this state",
                        "name": "is_active",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only drafts (true) or published forms (false)",
                        "name": "is_draft",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive title substring",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of forms to skip",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum number of forms to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Page of forms",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a form owned by the authenticated tenant. The slug must be unique across all forms. Forms are public and accept anonymous submissions unless public_available or accept_anonymous is false; a public form must accept anonymous submissions. With is_draft the form is saved as a draft: it is not available publicly until it is published by an update with is_draft false, and its content may be omitted. end_date is the deadline after which no submissions are accepted.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Create a form",
                "parameters": [
                    {
                        "description": "Form to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.FormRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Form created",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Slug already exists",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/forms/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns one of the authenticated tenant's forms.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Get a form",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Form",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid form ID",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Replaces every field of one of the authenticated tenant's forms. Omitted optional fields are cleared; an omitted is_active, public_available or accept_anonymous is true and an omitted is_draft is false, so saving a draft again needs is_draft true while omitting it publishes the form.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Update a form",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New state of the form",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.FormRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Form updated",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Slug already exists",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deletes one of the authenticated tenant's forms. Forms that have submissions or webhooks cannot be deleted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Delete a form",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Form deleted"
                    },
                    "400": {
                        "description": "Invalid form ID",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Form has submissions or webhooks",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/forms/{id}/submissions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Lists the submissions of one of the authenticated tenant's forms, newest first, with their metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "submissions"
                ],
                "summary": "List form submissions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of submissions to skip",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum number of submissions to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Page of submissions",
                        "schema": {
                            "$ref": "#/definitions/handlers.SubmissionListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/forms/{id}/webhooks": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Lists the active webhooks of one of the authenticated tenant's forms, oldest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "List webhooks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Webhooks",
                        "schema": {
                            "$ref": "#/definitions/handlers.WebhookListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid form ID",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Registers an endpoint notified of the form's new submissions. The target must be a public http(s) URL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Create a webhook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Webhook to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateWebhookRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Webhook created",
                        "schema": {
                            "$ref": "#/definitions/handlers.WebhookResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Reports whether the service is up and running.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is up",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/public/forms/{slug}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Returns the form with the given slug if it is published, active, its tenant is active and now is inside its availability window. Forms past their end_date (deadline) yield 410. Forms that are not public_available require a signed-in user (bearer token or Basic credentials); credentials are optional otherwise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Get a form to fill in",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Form",
                        "schema": {
                            "$ref": "#/definitions/handlers.PublicFormResponse"
                        }
                    },
                    "401": {
                        "description": "Private form and not signed in, or invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found or not available",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "410": {
                        "description": "Form closed: its end_date has passed",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/public/forms/{slug}/submissions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Stores the answers to a form that can currently be filled in, along with the client's IP address, user agent and referer. Forms that are not public_available require a signed-in user (bearer token or Basic credentials). The submitter's user ID is recorded only by forms that do not accept_anonymous.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "submissions",
                    "public"
                ],
                "summary": "Submit a form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Answers",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateSubmissionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Submission stored",
                        "schema": {
                            "$ref": "#/definitions/handlers.SubmissionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Sign-in required, or invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Form not found or not available",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "410": {
                        "description": "Form closed: its end_date has passed",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/samples/admin": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Requires the ADMIN role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "samples"
                ],
                "summary": "Admin sample",
                "responses": {
                    "200": {
                        "description": "Greeting",
                        "schema": {
                            "$ref": "#/definitions/handlers.SampleResponse"
                        }
                    },
                    "401": {
                        "description": "Not signed in",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Role not allowed",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/samples/form-creator": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Requires the FORM_CREATOR role (ADMIN passes every role check).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "samples"
                ],
                "summary": "Form creator sample",
                "responses": {
                    "200": {
                        "description": "Greeting",
                        "schema": {
                            "$ref": "#/definitions/handlers.SampleResponse"
                        }
                    },
                    "401": {
                        "description": "Not signed in",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Role not allowed",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/samples/public": {
            "get": {
                "description": "Can be called by anyone. Credentials are optional, but rejected when invalid.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "samples"
                ],
                "summary": "Public sample",
                "responses": {
                    "200": {
                        "description": "Greeting",
                        "schema": {
                            "$ref": "#/definitions/handlers.SampleResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/samples/signed-in": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Requires a signed-in user of any role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "samples"
                ],
                "summary": "Signed-in sample",
                "responses": {
                    "200": {
                        "description": "Greeting",
                        "schema": {
                            "$ref": "#/definitions/handlers.SampleResponse"
                        }
                    },
                    "401": {
                        "description": "Not signed in",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/tenants": {
            "post": {
                "description": "Registers a new tenant and returns it with a freshly generated API key. The key is shown only once; send it in the X-API-Key header of authenticated requests.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenants"
                ],
                "summary": "Create a tenant",
                "parameters": [
                    {
                        "description": "Tenant to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateTenantRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tenant created",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateTenantResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/tenants/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the tenant that owns the API key of the request.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenants"
                ],
                "summary": "Get the current tenant",
                "responses": {
                    "200": {
                        "description": "Authenticated tenant",
                        "schema": {
                            "$ref": "#/definitions/handlers.TenantResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Lists every user by ID. Requires the ADMIN role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Number of users to skip",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum number of users to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Page of users",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not signed in",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not an admin",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/role": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Sets the role of another user. Requires the ADMIN role; admins cannot change their own role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Change the role of a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New role",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SetRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User updated",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not signed in",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not an admin",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.Role": {
            "type": "string",
            "enum": [
                "ADMIN",
                "FORM_CREATOR",
                "BASIC",
                "BASIC"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleFormCreator",
                "RoleBasic",
                "DefaultRole"
            ]
        },
        "errors.Code": {
            "type": "string",
            "enum": [
                "invalid_argument",
                "unauthorized",
                "forbidden",
                "not_found",
                "conflict",
                "gone",
                "internal"
            ],
            "x-enum-varnames": [
                "CodeInvalidArgument",
                "CodeUnauthorized",
                "CodeForbidden",
                "CodeNotFound",
                "CodeConflict",
                "CodeGone",
                "CodeInternal"
            ]
        },
        "errors.HTTPErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/errors.Code"
                        }
                    ],
                    "example": "not_found"
                },
                "message": {
                    "type": "string",
                    "example": "form not found"
                }
            }
        },
        "handler.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "UP"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                }
            }
        },
        "handlers.CreateSubmissionRequest": {
            "type": "object",
            "properties": {
                "completion_time_seconds": {
                    "description": "CompletionTimeSeconds is how long the respondent took to fill the form in.",
                    "type": "integer",
                    "minimum": 0,
                    "example": 95
                },
                "payload": {
                    "description": "Payload holds the answers; any JSON value but null.",
                    "type": "object"
                }
            }
        },
        "handlers.CreateTenantRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Acme Inc."
                }
            }
        },
        "handlers.CreateTenantResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string",
                    "example": "3f1c...e9a0"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Acme Inc."
                }
            }
        },
        "handlers.CreateWebhookRequest": {
            "type": "object",
            "properties": {
                "secret_token": {
                    "description": "SecretToken, when set, is used to sign deliveries. It is never returned.",
                    "type": "string",
                    "example": "s3cr3t"
                },
                "target_url": {
                    "description": "TargetURL must be a public http(s) URL.",
                    "type": "string",
                    "example": "https://example.com/hooks/forms"
                }
            }
        },
        "handlers.FileResponse": {
            "type": "object",
            "properties": {
                "checksum_sha256": {
                    "description": "Checksum is the hex-encoded SHA-256 of the content.",
                    "type": "string",
                    "example": "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
                },
                "content_type": {
                    "type": "string",
                    "example": "image/png"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "0b6a3b2e-8f1c-4c4e-9d5e-2f1a7c3b9e10"
                },
                "name": {
                    "type": "string",
                    "example": "logo.png"
                },
                "size": {
                    "type": "integer",
                    "example": 2048
                },
                "url": {
                    "type": "string",
                    "example": "/files/0b6a3b2e-8f1c-4c4e-9d5e-2f1a7c3b9e10"
                }
            }
        },
        "handlers.FormDetailsResponse": {
            "type": "object",
            "properties": {
                "accept_anonymous": {
                    "type": "boolean",
                    "example": true
                },
                "content": {
                    "type": "object"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Get in touch with our team"
                },
                "end_date": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "is_draft": {
                    "type": "boolean",
                    "example": false
                },
                "public_available": {
                    "type": "boolean",
                    "example": true
                },
                "slug": {
                    "type": "string",
                    "example": "contact-us"
                },
                "start_date": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "tenant_id": {
                    "type": "integer",
                    "example": 1
                },
                "tenant_name": {
                    "type": "string",
                    "example": "Acme Inc."
                },
                "title": {
                    "type": "string",
                    "example": "Contact us"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                }
            }
        },
        "handlers.FormListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.FormSummaryResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handlers.FormRequest": {
            "type": "object",
            "properties": {
                "accept_anonymous": {
                    "description": "AcceptAnonymous forms store submissions without the submitter's\nidentity; defaults to true and must be true for public forms.",
                    "type": "boolean",
                    "example": true
                },
                "content": {
                    "description": "Content is the form definition (fields, layout); any JSON value but null.",
                    "type": "object"
                },
                "description": {
                    "type": "string",
                    "example": "Get in touch with our team"
                },
                "end_date": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "is_active": {
                    "description": "IsActive defaults to true when omitted.",
                    "type": "boolean",
                    "example": true
                },
                "is_draft": {
                    "description": "IsDraft saves the form without publishing it: drafts cannot be read or\nfilled in publicly, and their content may be omitted. Defaults to false.",
                    "type": "boolean",
                    "example": false
                },
                "public_available": {
                    "description": "PublicAvailable forms can be read and filled in without signing in;\ndefaults to true.",
                    "type": "boolean",
                    "example": true
                },
                "slug": {
                    "type": "string",
                    "example": "contact-us"
                },
                "start_date": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Contact us"
                }
            }
        },
        "handlers.FormResponse": {
            "type": "object",
            "properties": {
                "accept_anonymous": {
                    "type": "boolean",
                    "example": true
                },
                "content": {
                    "type": "object"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Get in touch with our team"
                },
                "end_date": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "is_draft": {
                    "type": "boolean",
                    "example": false
                },
                "public_available": {
                    "type": "boolean",
                    "example": true
                },
                "slug": {
                    "type": "string",
                    "example": "contact-us"
                },
                "start_date": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "tenant_id": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Contact us"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                }
            }
        },
        "handlers.FormSummaryResponse": {
            "type": "object",
            "properties": {
                "accept_anonymous": {
                    "type": "boolean",
                    "example": true
                },
                "content": {
                    "type": "object"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Get in touch with our team"
                },
                "end_date": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "is_draft": {
                    "type": "boolean",
                    "example": false
                },
                "public_available": {
                    "type": "boolean",
                    "example": true
                },
                "slug": {
                    "type": "string",
                    "example": "contact-us"
                },
                "start_date": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "submission_count": {
                    "type": "integer",
                    "example": 42
                },
                "tenant_id": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Contact us"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                }
            }
        },
        "handlers.MetadataResponse": {
            "type": "object",
            "properties": {
                "completion_time_seconds": {
                    "type": "integer",
                    "example": 95
                },
                "ip_address": {
                    "type": "string",
                    "example": "203.0.113.7"
                },
                "referer": {
                    "type": "string",
                    "example": "https://example.com/contact"
                },
                "user_agent": {
                    "type": "string",
                    "example": "Mozilla/5.0"
                }
            }
        },
        "handlers.PublicFormResponse": {
            "type": "object",
            "properties": {
                "accept_anonymous": {
                    "description": "AcceptAnonymous is false for forms recording who submitted them.",
                    "type": "boolean",
                    "example": true
                },
                "content": {
                    "type": "object"
                },
                "description": {
                    "type": "string",
                    "example": "Get in touch with our team"
                },
                "end_date": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "public_available": {
                    "description": "PublicAvailable is false for forms that require signing in.",
                    "type": "boolean",
                    "example": true
                },
                "slug": {
                    "type": "string",
                    "example": "contact-us"
                },
                "title": {
                    "type": "string",
                    "example": "Contact us"
                }
            }
        },
        "handlers.SampleResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Hello, alice"
                },
                "policy": {
                    "description": "Policy describes who may call the endpoint.",
                    "type": "string",
                    "example": "signed in"
                },
                "user": {
                    "description": "User is the signed-in caller; null for anonymous calls.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    ]
                }
            }
        },
        "handlers.SetRoleRequest": {
            "type": "object",
            "properties": {
                "role": {
                    "enum": [
                        "ADMIN",
                        "FORM_CREATOR",
                        "BASIC"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/auth.Role"
                        }
                    ],
                    "example": "FORM_CREATOR"
                }
            }
        },
        "handlers.SignUpRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "Password is 8 to 72 bytes long.",
                    "type": "string",
                    "example": "correct horse battery"
                },
                "username": {
                    "description": "Username is case-insensitive: 3 to 50 letters, digits, '.', '_' or '-'.",
                    "type": "string",
                    "example": "alice"
                }
            }
        },
        "handlers.SubmissionListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.SubmissionResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "handlers.SubmissionResponse": {
            "type": "object",
            "properties": {
                "form_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "metadata": {
                    "$ref": "#/definitions/handlers.MetadataResponse"
                },
                "payload": {
                    "type": "object"
                },
                "submitted_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "user_id": {
                    "description": "UserID is the signed-in submitter; null for anonymous submissions.",
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "handlers.TenantResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Acme Inc."
                }
            }
        },
        "handlers.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "AccessToken is a JWT; send it as \"Authorization: Bearer \u003ctoken\u003e\".",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "expires_at": {
                    "type": "string",
                    "example": "2026-01-01T01:00:00Z"
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                },
                "user": {
                    "$ref": "#/definitions/handlers.UserResponse"
                }
            }
        },
        "handlers.UserListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.UserResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "handlers.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "role": {
                    "enum": [
                        "ADMIN",
                        "FORM_CREATOR",
                        "BASIC"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/auth.Role"
                        }
                    ],
                    "example": "BASIC"
                },
                "username": {
                    "type": "string",
                    "example": "alice"
                }
            }
        },
        "handlers.WebhookListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.WebhookResponse"
                    }
                }
            }
        },
        "handlers.WebhookResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                },
                "form_id": {
                    "type": "integer",
                    "example": 1
                },
                "has_secret": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "target_url": {
                    "type": "string",
                    "example": "https://example.com/hooks/forms"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key of the tenant, returned when the tenant is created.",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "description": "JWT returned by POST /auth/signin, sent as \"Bearer \u003ctoken\u003e\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "App API",
	Description:      "Username and password of a user: \"Basic \" + btoa(username + \":\" + password).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
