-- migrate:up
-- Accounts signing in with a username and password. The role grants access to
-- the protected routes; new accounts are BASIC.
CREATE TYPE "user_role" AS ENUM ('ADMIN', 'FORM_CREATOR', 'BASIC');

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Stored lowercase so sign-in is case-insensitive.
  "username" varchar(50) UNIQUE NOT NULL CHECK ("username" = lower("username")),
  "password_hash" varchar(255) NOT NULL,
  "role" user_role NOT NULL DEFAULT 'BASIC',
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

-- public_available: the form can be read and filled in without signing in.
-- accept_anonymous: submissions are stored without the submitter's identity.
-- A public form cannot require an identity, since anyone may fill it in.
ALTER TABLE "forms"
  ADD COLUMN "public_available" boolean NOT NULL DEFAULT true,
  ADD COLUMN "accept_anonymous" boolean NOT NULL DEFAULT true,
  ADD CONSTRAINT "forms_public_accepts_anonymous" CHECK (NOT "public_available" OR "accept_anonymous");

-- The signed-in submitter; NULL for anonymous submissions.
ALTER TABLE "form_submissions"
  ADD COLUMN "user_id" integer REFERENCES "users" ("id");

CREATE INDEX "form_submissions_user_id_idx" ON "form_submissions" ("user_id");

-- migrate:down
DROP INDEX IF EXISTS "form_submissions_user_id_idx";
ALTER TABLE "form_submissions" DROP COLUMN IF EXISTS "user_id";
ALTER TABLE "forms"
  DROP CONSTRAINT IF EXISTS "forms_public_accepts_anonymous",
  DROP COLUMN IF EXISTS "accept_anonymous",
  DROP COLUMN IF EXISTS "public_available";
DROP TABLE IF EXISTS "users";
DROP TYPE IF EXISTS "user_role";
