-- migrate:up
-- Users created through OIDC sign-in have no password.
ALTER TABLE "users" ALTER COLUMN "password_hash" DROP NOT NULL;

-- External OpenID Connect identities linked to a user. (issuer, subject) is
-- the stable identifier of a person at a provider; the email is informative
-- only and never used to find or link accounts.
CREATE TABLE "user_identities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "issuer" varchar(255) NOT NULL,
  "subject" varchar(255) NOT NULL,
  "email" varchar(320),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "last_login_at" timestamp NOT NULL DEFAULT (now()),
  UNIQUE ("issuer", "subject")
);

CREATE INDEX "user_identities_user_id_idx" ON "user_identities" ("user_id");

-- migrate:down
DROP TABLE IF EXISTS "user_identities";
-- Users without a password get an unusable hash, so NOT NULL can come back.
UPDATE "users" SET "password_hash" = '!' WHERE "password_hash" IS NULL;
ALTER TABLE "users" ALTER COLUMN "password_hash" SET NOT NULL;
